# Generated by Django 5.1.4 on 2025-01-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todo_completed_alter_todo_order_alter_todo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='order',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='url',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
